apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deploy
  labels:
    name: result-deploy
    app: voting-app-cluster
spec:
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: voting-app-cluster
    spec:
      containers:
      - name: result-app
        image: kodekloud/examplevotingapp_result:v1
        ports:
        - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      name: result-app-pod
      app: voting-app-cluster